title: Jamie Lu - Data Analytics | Design & Visualization
author: GitHub User
email: jamieqianhui@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  My personal blog. This is a space where I document my learnings, share data analytics concepts & codes and real estate related information with data enthusiasts! 

show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: Jamie Lu
  tagline: Data Analytics | Visualization & Design
  date_format: "%b %-d, %Y"
  analytics_id: 'UA-142135918-1'
  sitemap: true
  # dark_mode: true
  # search: true

  # generate social links in footer
  social_links:
    twitter: jamieprairie
    github:  jamieqianhui
    linkedIn: in/jamieluqh
    email: jekyll
    # rss: rss
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages: about.md

# Build settings
remote_theme: thelehhman/plainwhite-jekyll



plugins:
  - jekyll-seo-tag
#  - jekyll-feed
